import fs from "fs";
import path from "path";
import { defineConfig } from "tsup";

export default defineConfig(() => {
  return [
    {
      entry: {
        "boot": "src/boot.ts",
      },
      format: ["iife"],
      globalName: "T3M4Boot",
      minify: true,
      dts: false,
      sourcemap: false,
      async onSuccess() {
        const distFile = path.join(__dirname, "dist/boot.global.js");
        const outFile = path.join(__dirname, "src/generated/boot.ts");

        const content = fs.readFileSync(distFile, "utf8");
        const safe = content.replace(/`/g, "\\`");

        const ts = `
// AUTO-GENERATED BY tsup - DO NOT EDIT MANUALLY
export const T3M4_BOOT = \`${safe}\`;
`;
        fs.writeFileSync(outFile, ts, "utf8");
        console.log("✓ Generated boot.ts");
      },
    },
    {
      entry: ["src/index.ts", "src/generated/boot.ts"],
      sourcemap: false,
      minify: true,
      dts: true,
      clean: true,
      format: ["esm", "cjs"],
      splitting: false,
      bundle: true,
    },
  ];
});
