import { Footer } from '@/components/Footer'
import { Navbar } from '@/components/Navbar'
import { Providers } from '@/components/providers/Providers.server'
import { FontMono, FontSans } from '@/fonts'
import { cn } from '@/lib/utils'
import '@/styles/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params

  return (
    <html lang={locale} suppressHydrationWarning>
      <body  className={cn('min-h-svh flex flex-col antialiased', FontSans.variable, FontMono.variable)}>
        <Providers locale={locale}>
          <Navbar />
          <main className='flex-1'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
