import { Footer } from '@/components/Footer'
import { Navbar } from '@/components/Navbar'
import { Providers } from '@/components/providers/Providers.server'
import { FontMono, FontSans } from '@/fonts'
import { i18nRouting } from '@/lib/next-intl/routing'
import { cn } from '@/lib/utils'
import '@/styles/globals.css'
import { hasLocale, Locale } from 'next-intl'
import { setRequestLocale } from 'next-intl/server'
import { notFound } from 'next/navigation'
import { ReactNode } from 'react'

type Props = {
  children: ReactNode
  params: Promise<{ locale: Locale }>
}

export function generateStaticParams() {
  return i18nRouting.locales.map((locale) => ({ locale }))
}

export async function generateMetadata({ }: Omit<Props, 'children'>) {
  // const { locale } = await params
  // const t = await getTranslations({ locale, namespace: 'Index' })

  return {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
}

export default async function RootLayout({ children, params }: Readonly<Props>) {
  const { locale } = await params
  if (!hasLocale(i18nRouting.locales, locale)) notFound()

  setRequestLocale(locale)

  return (
    <html lang={locale} suppressHydrationWarning data-island='root'>
      <body className={cn('flex min-h-svh flex-col antialiased', FontSans.variable, FontMono.variable)}>
        <Providers locale={locale}>
          <Navbar />
          <main className='flex-1'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}