import { FontMono, FontSans } from '@/fonts'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import '@/styles/globals.css'
import { Providers } from '@/components/Providers.server'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={cn('min-h-svh antialiased', FontSans.variable, FontMono.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
