import { Metadata } from 'next'
import { ThemingProvider } from '../lib/next-themes'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ThemingProvider>{children}</ThemingProvider>
      </body>
    </html>
  )
}
